### ISSUE TITLE
Library import not working with ES2015

### ISSUE THREAD

**Issue by IjzerenHein** [zengabor/zenscroll#8] opened 2016-02-09 22:59 UTC
Hi, I'm trying to use your awesome library in an ES2015 project (babel, webpack & react), but there seems something wrong with the UMD definition of the zenscroll library. I've installed the library using NPM and am importing it like this:

`import zenscroll from 'zenscroll'`

This however doesn't work. When I inspect the result, it shows me this:

![image](https://cloud.githubusercontent.com/assets/6184593/12933372/0073490e-cf88-11e5-81d1-622962db97ea.png)

Inside the default export there is another `zenscroll` object, which is strange.

So, this let me to try to explicitly import that `zenscroll` export like this:

`import {zenscroll} from 'zenscroll'`

This allows me to call the `toY()` function, however now it gives this exception inside that function:

![image](https://cloud.githubusercontent.com/assets/6184593/12933475/7d26b36e-cf88-11e5-8560-f16db348715e.png)

When inspecting the `win` object, it gives me this information:

![image](https://cloud.githubusercontent.com/assets/6184593/12933516/c47fefc8-cf88-11e5-9f36-deb6f69a44e5.png)

My conclusion is that there is something oddly wrong with the UMD definition of this module.

I've put  my source-code online so you can have a closer look:
https://github.com/IjzerenHein/zenscroll-es6-issue

best regards,
Hein

**Comment by zengabor** [comment] 2016-02-10 19:00
Thank you @IjzerenHein 

I need to look into this. It is probably easy to fix but I need to understand it first.

**Comment by IjzerenHein** [comment] 2016-02-10 19:03
Awesome, if I can help in any way let me know.

You can reproduce the issue by running the demo, and clicking the 'Next' button (all the way at the bottom). The exception will show up in the console.
https://rawgit.com/IjzerenHein/zenscroll-es6-issue/master/www/index.html

cheers, Hein

**Comment by zengabor** [comment] 2016-02-10 21:06
Didn’t make a full investigation, just a quick look but I already suspect what the issue is. Currently the very last line of zenscroll.js is:

```
})(this, document);
```

For a quick fix you could try changing that line to:

```
})(window, document);
```

Let me know if it works for you.

**Comment by IjzerenHein** [comment] 2016-02-10 21:33
I've tried, but unfortunately it doesn't work.

**Comment by IjzerenHein** [comment] 2016-02-10 22:11
To elaborate. When I change `this` to `window`, other code breaks down. Since `win` no longer refers to the `window` object, calls like `win.scrollTo()` and `win.addEventListener()` now fail. When I modified these calls to use the window object explicitly it all works fine.

**Comment by re6exp** [comment] 2016-02-15 10:31
The library is not usable with webpack.

**Comment by zengabor** [comment] 2016-02-15 14:43
Sorry about that @re6exp and thanks for the info. Once I familiarized myself with these things, I can probably find a solution. :)

**Comment by zengabor** [comment] 2016-02-16 13:10
Looks like fixing this is very simple: what is currently assigned to `window` must be assigned to `module.exports` and then it will work in this module framework. So I need to wrap everything in a few `if` conditions to detect that environment.

I am going to release a new version, probably already tonight (in 10 hours or so).

It will be a new major version as the interface for new scrollers (e.g., `new Zenscroll(yourElement)`) must be slightly changed.

**Comment by IjzerenHein** [comment] 2016-02-16 13:14
Awesome, thanks a lot!

**Comment by zengabor** [comment] 2016-02-16 18:28
I am already testing the new version in the different browsers. So far it works alright in Chrome (Android & OS X), Safari (iOS & OS X). No functional change, just this little re-packaging.

If you want you can already grab the "beta" here: https://github.com/zengabor/zenscroll/blob/gh-pages/zenscroll.js

**Comment by zengabor** [comment] 2016-02-16 22:48
Just released 3.0.0 which should fix the issue, @IjzerenHein and @re6exp

**Closed as completed by zengabor** 2016-02-16 22:48 UTC

**Comment by IjzerenHein** [comment] 2016-02-17 07:08
Nice, I just confirmed that the problem has been fixed.
Using `import zenscroll from 'zenscroll'` now works as expected.

Thanks very much! :)

**Comment by zengabor** [comment] 2016-02-17 07:10
Thanks for reporting and sorry about the trouble. 

Note that I just released 3.0.1 with improved detection of the native smooth-scroll setting in the browser.

**Comment by re6exp** [comment] 2016-02-20 12:25
Works great!
Thank you!

**Comment by lnorton89** [comment] 2018-06-10 17:09
I'm experiencing this issue on 4.0.2 with webpack 4.10.2. Any chance this has come back?

```import zenscroll from 'zenscroll'``` is my import.
