### ISSUE TITLE
Issue with using e.preventDefault()

### ISSUE THREAD

**Issue by dotnetshadow** [zengabor/zenscroll#37] opened 2017-04-27 00:23 UTC
I noticed that when I use zenscroll, if I have an anchor tag such as

`<a id="test" href="#">Click Me</a>`

and if I have jquery event attached to this

`$('#test').on('click', function (e) { 
    e.preventDefault();
    console.log('test');
});`

That in fact the **e.preventDefault()** doesn't work, in that it shows the # in the url.

I'm either forced to remove the # in the anchor or I have to use return false in my function.

I suspect it has to do with how you detect hashes on page load

I understand you discussed something similar here:
https://github.com/zengabor/zenscroll/issues/13

But my understanding is that e.preventDefault() should of worked?

**Comment by zengabor** [comment] 2017-04-27 17:06
The short answer would be that yes, that looks like a misuse of an anchor tag, you should use something else, probably a `<button id="test">Click Me</button>` or maybe a `<span id="test">Click Me</span>` instead.

Regarding the expectation on `preventDefault()`: it only prevents the browser's default handling, but not other event handlers. It has a sister though, it's called `stopPropagation()` which will indeed stop event handlers, like Zenscroll, that are further down on the bubbling phase. But using this would be only fixing the symptom, not the root cause. I think the real fix would be changing the anchor to a `<button>` or `<span>`. :)

**Comment by dotnetshadow** [comment] 2017-04-28 09:13
Yeah that makes sense.

I was more thinking that lots of people probably make the same mistake and that if they have in their existing javascript e.preventdefault() and suddenly it stops working everywhere just because they added zenscroll, then it could be problematic

**Comment by zengabor** [comment] 2017-04-29 08:17
Yeah, that's a good point, I will add it to the README. Thanks for that!

**Comment by Finesse** [comment] 2018-03-01 06:34
@zengabor This issue can be fixed in a really simple way. Add this code to the beginning of the window click listener:

```js
if (event.defaultPrevented) {
    return
}
```

It checks whether the click event default was prevented and exits if it was.

**Closed as completed** 2022-07-09 15:18 UTC
